apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hfqejcpcv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hfqejcpcv-nodejs 
  name: hfqejcpcv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hfqejcpcv-nodejs 
