apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hfqejcpcv-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:d357e96e06a22ca421876d76ebdf327b5aa90cdf@sha256:047f8d29c7421ccf99ad4a745b264c4e8b7da56652f8ee7553c3b95d32c23f7a
          name: container-image
